server:
  port: 5002

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-all:3306/UserMySQL
    username: root
    password: admin123

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /

mybatis:
  #指定mybatis用哪个配置文件
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka